### ISSUE TITLE
Compiling the repo

### ISSUE THREAD

**Issue by whiteyhat** [tlhunter/Cobalt-Calibur-3#62]
Hey!

Can you help me out to compile this repo? The screen is black in the same way as in [http://cobaltcalibur.net](http://cobaltcalibur.net)

**Comment by tlhunter** [comment]
Unfortunately this project has suffered from some major bit rot. It was one of my early Node.js projects and is a big pile of spaghetti code. It'll take some time for me to modernize it and properly document the installation, and I have no ETA on that.

**Comment by whiteyhat** [comment]
Oh @tlhunter I see. If there is anything I can help to modernize let me know. I would like to fork it to integrate bitcoin payments within this project and run it on [Satoshis.Games](https://satoshis.games/)

**Comment by mmccall0813** [comment]
@whiteyhat so you're wanting to accept donations for a project you didn't create?

**Comment by whiteyhat** [comment]
> @whiteyhat so you're wanting to accept donations for a project you didn't create?

I never said that

**Comment by mmccall0813** [comment]
> I never said that

Oh sorry, I must have misinterpreted what you meant when you said "I would like to fork it to integrate bitcoin payments". My bad.
